services:
  smt:
    build:
      context: .
      args:
        INSTALL_DEV: "true"
    container_name: ${PROJECT_NAME}-backend
    volumes:
      - ./smt:/code/smt
      - ./alembic.ini:/code/alembic.ini
      - ./alembic:/code/alembic
      - ./logs/web:/code/logs
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    command: ["python", "/code/smt/main.py"]
    depends_on:
      - db
      - redis
    restart: no

  worker:
    build:
      context: .
      args:
        INSTALL_DEV: "false"
    container_name: ${PROJECT_NAME}-worker
    volumes:
      - ./smt:/code/smt
      - ./logs/worker:/code/logs
    env_file:
      - .env
    command: ["arq", "smt.worker.settings.WorkerSettings"]
    depends_on:
      - db
      - redis
    restart: no

  db:
    image: postgres:16
    container_name: ${PROJECT_NAME}-db
    env_file:
      - .env.db
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: no

  redis:
    image: redis:alpine
    container_name: ${PROJECT_NAME}-redis
    volumes:
      - redis-data:/data
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    restart: no

volumes:
  postgres-data:
  redis-data: