services:
  smt:
    build: .
    volumes:
      - ./smt:/code/smt
      - ./alembic.ini:/code/alembic.ini
      - ./alembic:/code/alembic
    container_name: ${PROJECT_NAME}-backend
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    command: ["python", "/code/smt/main.py"]
    depends_on:
      - db
    restart: on-failure

  db:
    image: postgres:16
    container_name: ${PROJECT_NAME}-db
    env_file:
      - .env.db
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: ${PROJECT_NAME}-redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    restart: unless-stopped

  celery:
    build: .
    container_name: ${PROJECT_NAME}-celery
    command: celery -A smt.celery_app worker --loglevel=info
    volumes:
      - ./smt:/code/smt
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  pgdata:
