"""add bought_at and listed_at fields to position table

Revision ID: 3fd8281e4211
Revises: 071a43d080c1
Create Date: 2025-07-11 11:34:50.038881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fd8281e4211'
down_revision: Union[str, None] = '071a43d080c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('bought_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('positions', sa.Column('listed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('positions', 'listed_at')
    op.drop_column('positions', 'bought_at')
    # ### end Alembic commands ###
