"""add trading settings table

Revision ID: 622ac9eafe53
Revises: fa5a3ab71829
Create Date: 2025-06-19 15:59:15.389033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '622ac9eafe53'
down_revision: Union[str, None] = 'fa5a3ab71829'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trading_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('min_profit_threshold', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('min_profit_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('max_investment_per_item', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('buy_percentile', sa.Integer(), nullable=False),
    sa.Column('sell_percentile', sa.Integer(), nullable=False),
    sa.Column('min_volume_24h', sa.Integer(), nullable=False),
    sa.Column('min_volume_7d', sa.Integer(), nullable=False),
    sa.Column('max_volatility_threshold', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('min_volatility_threshold', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('price_history_days', sa.Integer(), nullable=False),
    sa.Column('analysis_window_days', sa.Integer(), nullable=False),
    sa.Column('max_concurrent_trades', sa.Integer(), nullable=False),
    sa.Column('cooldown_after_loss_hours', sa.Integer(), nullable=False),
    sa.Column('price_refresh_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('stats_refresh_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('emergency_stop', sa.Boolean(), nullable=False),
    sa.Column('max_daily_loss', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trading_settings')
    # ### end Alembic commands ###
