"""decrease accuracy

Revision ID: 6ffd2e64a5a7
Revises: 1c8e7a9a7917
Create Date: 2025-07-11 14:20:45.731178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ffd2e64a5a7'
down_revision: Union[str, None] = '1c8e7a9a7917'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pool_items', 'volatility',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Numeric(precision=10, scale=3),
               existing_nullable=True)
    op.alter_column('price_history_record', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Numeric(precision=10, scale=3),
               existing_nullable=False)
    op.alter_column('trading_settings', 'max_volatility_threshold',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Numeric(precision=10, scale=3),
               existing_nullable=False)
    op.alter_column('trading_settings', 'min_volatility_threshold',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Numeric(precision=10, scale=3),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trading_settings', 'min_volatility_threshold',
               existing_type=sa.Numeric(precision=10, scale=3),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=False)
    op.alter_column('trading_settings', 'max_volatility_threshold',
               existing_type=sa.Numeric(precision=10, scale=3),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=False)
    op.alter_column('price_history_record', 'price',
               existing_type=sa.Numeric(precision=10, scale=3),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=False)
    op.alter_column('pool_items', 'volatility',
               existing_type=sa.Numeric(precision=10, scale=3),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=True)
    # ### end Alembic commands ###
