"""create item_stats

Revision ID: a2831d43b4ab
Revises: 77aa3f81333e
Create Date: 2025-06-03 14:28:11.441353

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a2831d43b4ab"
down_revision: Union[str, None] = "77aa3f81333e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "item_stats",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("market_hash_name", sa.String(length=255), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("volume", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["market_hash_name"], ["pool_items.market_hash_name"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("item_stats")
    # ### end Alembic commands ###
