"""remove quantity; add asset id

Revision ID: a2e48825e292
Revises: 230e00c2d5d1
Create Date: 2025-07-06 21:25:12.697778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2e48825e292'
down_revision: Union[str, None] = '230e00c2d5d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('asset_id', sa.String(length=32), nullable=True))
    op.create_unique_constraint(None, 'positions', ['asset_id'])
    op.drop_column('positions', 'quantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'positions', type_='unique')
    op.drop_column('positions', 'asset_id')
    # ### end Alembic commands ###
