"""add uniqueness contraint

Revision ID: be504f24c012
Revises: a2831d43b4ab
Create Date: 2025-06-03 14:51:58.024999

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "be504f24c012"
down_revision: Union[str, None] = "a2831d43b4ab"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_item_stats_item_time", "item_stats", ["market_hash_name", "recorded_at"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_item_stats_item_time", "item_stats", type_="unique")
    # ### end Alembic commands ###
