"""add new fields to PoolItem

Revision ID: d8f4c4baeb30
Revises: c7a499120ddf
Create Date: 2025-06-04 11:34:08.454896

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d8f4c4baeb30"
down_revision: Union[str, None] = "c7a499120ddf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("pool_items", sa.Column("current_lowest_price", sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column("pool_items", sa.Column("current_median_price", sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column("pool_items", sa.Column("current_volume24h", sa.Integer(), nullable=True))
    op.alter_column(
        "pool_items",
        "buy_price",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=10, scale=2),
        existing_nullable=True,
    )
    op.alter_column(
        "pool_items",
        "sell_price",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=10, scale=2),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "pool_items",
        "sell_price",
        existing_type=sa.Numeric(precision=10, scale=2),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "pool_items",
        "buy_price",
        existing_type=sa.Numeric(precision=10, scale=2),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.drop_column("pool_items", "current_volume24h")
    op.drop_column("pool_items", "current_median_price")
    op.drop_column("pool_items", "current_lowest_price")
    # ### end Alembic commands ###
