"""add app_id and context_id to pool items

Revision ID: f1e610cd5955
Revises: d8f4c4baeb30
Create Date: 2025-06-04 12:24:33.948473

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f1e610cd5955"
down_revision: Union[str, None] = "d8f4c4baeb30"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("pool_items", sa.Column("app_id", sa.String(length=32), nullable=False))
    op.add_column("pool_items", sa.Column("context_id", sa.String(length=64), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pool_items", "context_id")
    op.drop_column("pool_items", "app_id")
    # ### end Alembic commands ###
