"""add new indicator fields to pool item table

Revision ID: fa5a3ab71829
Revises: 15e900b450d0
Create Date: 2025-06-15 14:41:15.119423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa5a3ab71829'
down_revision: Union[str, None] = '15e900b450d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pool_items', sa.Column('optimal_buy_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('pool_items', sa.Column('optimal_sell_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('pool_items', sa.Column('manual_buy_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('pool_items', sa.Column('manual_sell_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('pool_items', sa.Column('volatility', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('pool_items', sa.Column('potential_profit', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('pool_items', sa.Column('use_for_trading', sa.Boolean(), nullable=False))
    op.create_index('ix_pool_items_use_for_trading', 'pool_items', ['use_for_trading'], unique=False)
    op.drop_column('pool_items', 'sell_price')
    op.drop_column('pool_items', 'buy_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pool_items', sa.Column('buy_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('pool_items', sa.Column('sell_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.drop_index('ix_pool_items_use_for_trading', table_name='pool_items')
    op.drop_column('pool_items', 'use_for_trading')
    op.drop_column('pool_items', 'potential_profit')
    op.drop_column('pool_items', 'volatility')
    op.drop_column('pool_items', 'manual_sell_price')
    op.drop_column('pool_items', 'manual_buy_price')
    op.drop_column('pool_items', 'optimal_sell_price')
    op.drop_column('pool_items', 'optimal_buy_price')
    # ### end Alembic commands ###
